version: '3.1'
services:
  mycentos:
    image: sh827kim/pgcentos:2
    container_name: mycentos
    privileged: true
    restart: always
    ports:
      - "15432:5432"
    volumes:
      - YOUR_DATA_DIR:/var/lib/pgsql/14
      - YOUR_ARCHIVE_DIR:/mnt/server/archivedir
